name: Actualizar Actividad Reciente

on:
  schedule:
    - cron: "* */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4

      - name: GitHub - Activity - Readme
        uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
